### ISSUE TITLE
Failed to activate the ide-typescript package

### ISSUE THREAD

**Issue by rajanbhadauria** [atom/ide-typescript#133]
A few things to know before you create an issue

* This package requires [Atom 1.21](https://atom.io)
* We launch a "language server" process on your machine that understands the language you are editing
* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control
* You can see what the language server supports by checking out our README and following the link after "powered by"
* "disconnected", "JSONRPC" or "Content-Header" errors indicate that server process died. We're working on better recovery right now

If you have understood all this, please remove this text and start writing your issue :)

**Comment by rajanbhadauria** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Ubuntu 18.04.1
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.7


### Stack Trace

Failed to activate the ide-typescript package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at TypeScriptLanguageClient.getProjectPath (/packages/ide-typescript/lib/main.js:48:80)
    at TypeScriptLanguageClient.shouldStartForEditor (/packages/ide-typescript/lib/main.js:41:45)
    at /packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:210:122)
    at ServerManager._handleGrammarChange (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:74:18)
    at editor.observeGrammar (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:67)
    at TextEditor.observeGrammar (/usr/share/atom/resources/app/src/text-editor.js:753:11)
    at ServerManager.observeTextEditors (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:33)
    at Set.forEach (<anonymous>)
    at TextEditorRegistry.observe (/usr/share/atom/resources/app/src/text-editor-registry.js:135:24)
    at ServerManager.startListening (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:37:51)
    at TypeScriptLanguageClient.activate (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:211:29)
    at Package.activateNow (/usr/share/atom/resources/app/src/package.js:230:33)
    at measure (/usr/share/atom/resources/app/src/package.js:206:33)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at activationPromise.Promise (/usr/share/atom/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:696:42)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

### Commands

```
  8x -4:38 core:backspace (input.hidden-input)
     -3:28 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:19.6.0 application:add-project-folder (div.panels-item)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-ide-ui 0.5.3 
atom-typescript 12.6.3 
ide-typescript 0.7.7 
```

**Comment by borkie** [comment]
Same here:

`[Enter steps to reproduce:]

1. Open Atom

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.14
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.7


### Stack Trace

Failed to activate the ide-typescript package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at TypeScriptLanguageClient.getProjectPath (/packages/ide-typescript/lib/main.js:48:80)
    at TypeScriptLanguageClient.shouldStartForEditor (/packages/ide-typescript/lib/main.js:41:45)
    at /packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:210:122)
    at ServerManager._handleGrammarChange (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:74:18)
    at editor.observeGrammar (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:67)
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:753:11)
    at ServerManager.observeTextEditors (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:33)
    at Set.forEach (<anonymous>)
    at TextEditorRegistry.observe (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:135:24)
    at ServerManager.startListening (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:37:51)
    at TypeScriptLanguageClient.activate (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:211:29)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:696:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:671:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:669:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:648:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
docblockr 0.13.7 
file-icons 2.1.25 
highlight-selected 0.14.0 
ide-php 0.7.15 
ide-typescript 0.7.7 
markdown-preview-plus 3.7.0 
monokai-neo-syntax 1.3.2 
pigments 0.40.2 
```

`

**Comment by jrotondo-madaket** [comment]
Same here:

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.7


### Stack Trace

Failed to activate the ide-typescript package

```
At Cannot read property 'path' of undefined

TypeError: Cannot read property 'path' of undefined
    at TypeScriptLanguageClient.getProjectPath (/packages/ide-typescript/lib/main.js:48:80)
    at TypeScriptLanguageClient.shouldStartForEditor (/packages/ide-typescript/lib/main.js:41:45)
    at /packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:210:122)
    at ServerManager._handleGrammarChange (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:74:18)
    at editor.observeGrammar (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:67)
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:753:11)
    at ServerManager.observeTextEditors (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:52:33)
    at Set.forEach (<anonymous>)
    at TextEditorRegistry.observe (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:135:24)
    at ServerManager.startListening (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:37:51)
    at TypeScriptLanguageClient.activate (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/auto-languageclient.js:211:29)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:696:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:671:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:669:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:648:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:875:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-ide-ui 0.13.0 
atom-typescript 12.6.3 
busy-signal 1.4.3 
highlight-selected 0.14.0 
ide-typescript 0.7.7 
intentions 1.1.5 
language-freemarker 0.2.0 
less-than-slash 0.18.0 
linter 2.2.0 
linter-csslint 2.0.1 
linter-sass-lint 1.8.3 
linter-tslint 1.9.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.0 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
symbol-gen 1.3.1 
```

**Comment by damieng** [comment]
Can you try and see if setting the ignoreFlow config setting to false hope
n the ide-typescript config avoids this error? You might need to restart
atom after setting it.

**Comment by jrotondo-madaket** [comment]
How do I go about doing that, DamienG?

**Comment by jrotondo-madaket** [comment]
That might have actually helped DamienG. After switching that setting to false and rebooting, I am not getting that error.

**Comment by damieng** [comment]
Cool, thanks for the update. I'll see if I can dig in and fix it.

**Comment by damieng** [comment]
I can only repro this if I open a typescript or JS file without first opening a folder.  

I will put a fix in to avoid generating an error for such a scenario but the whole concept of atom-ide is based around opening the root folder so you'll need to open the root folder in the future to take full advantage of the features.

**Comment by damieng** [comment]
Update will go out later tonight.

**Comment by damieng** [comment]
Pushed out the fix in 0.7.8

**Comment by tylerbwilliams** [comment]
Just got the error with 0.7.8 installed as well.  Turned off "Ignore Flow project folders", still getting the error

**Comment by tylerbwilliams** [comment]
![image](https://user-images.githubusercontent.com/11303563/46767533-da133a80-ccaa-11e8-80b7-75f2b12c1d22.png)
