### ISSUE TITLE
TSLint doesn't obey the tsconfig.json

### ISSUE THREAD

**Issue by wolfy1339** [atom/ide-typescript#135]
When using this package, TSLint will complain about async functions, even though I included the `es2015` in my `tsconfig.json` file.
Even VSCode gets this right

Here's the error message from the linter:
```
An async function or method in ES5/ES3 requires the 'Promise' constructor. Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
```

apm version:
```
$ apm --version
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at EventEmitter.<anonymous> (C:\Users\Thomas2\AppData\Local\atom\app-1.34.0-nightly3\resources\app\apm\lib\apm-cli.js:169:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
atom version:
```
$ atom --version

Atom    : 1.34.0-nightly3
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by ssribeiro** [comment]
same here with new update

**Comment by wolfy1339** [comment]
This is no longer a problem with 0.8.0
