### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by liwens** [atom/ide-typescript#136]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.9

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\Administrator\.atom\packages\ide-typescript\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
  2x -2:52.4.0 core:cut (input.hidden-input)
  2x -2:33.9.0 core:backspace (input.hidden-input)
     -2:33.1.0 core:move-up (input.hidden-input)
     -2:32.5.0 core:cut (input.hidden-input)
  2x -2:30.6.0 core:save (input.hidden-input)
     -2:16.1.0 core:cut (input.hidden-input)
     -2:15.8.0 core:undo (input.hidden-input)
     -2:13.8.0 core:cut (input.hidden-input)
     -2:12.8.0 core:paste (input.hidden-input)
     -2:12.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-ternjs 0.18.3 
atom-typescript 12.6.3 
autocomplete-paths 2.12.2 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.21 
highlight-selected 0.13.1 
ide-typescript 0.7.9 
language-vue 0.23.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
simplified-chinese-menu 5.3.5 
svn 0.0.13 
tortoise-svn 0.5.1 
```

**Comment by damieng** [comment]
Should be fixed in the new ide-typescript 0.8.0 update.
