### ISSUE TITLE
When installing 0.7.9

### ISSUE THREAD

**Issue by adammenges** [atom/ide-typescript#137]
I see this:

<img width="738" alt="screen shot 2018-10-27 at 7 23 37 pm" src="https://user-images.githubusercontent.com/817438/47611212-3c479b80-da1e-11e8-9c6e-fca60a89b85f.png">

Full log:

``` bash
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/adammenges/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/adammenges/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/ide-typescript/versions/0.7.9/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.7',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 22a418268893871b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/ide-typescript/versions/0.7.9/tarball 6817ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/ide-typescript/versions/0.7.9/tarball fetched in 6832ms
9 timing stage:loadCurrentTree Completed in 7027ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule ide-typescript@0.7.9 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-languageclient 92ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/javascript-typescript-langserver 98ms (from cache)
19 silly pacote version manifest for atom-languageclient@0.9.7 fetched in 103ms
20 silly resolveWithNewModule atom-languageclient@0.9.7 checking installable status
21 silly pacote range manifest for javascript-typescript-langserver@^2.7.0 fetched in 104ms
22 silly resolveWithNewModule javascript-typescript-langserver@2.11.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/fuzzaldrin-plus 24ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/vscode-languageserver-protocol 24ms (from cache)
25 silly pacote range manifest for fuzzaldrin-plus@^0.6.0 fetched in 27ms
26 silly resolveWithNewModule fuzzaldrin-plus@0.6.0 checking installable status
27 silly pacote version manifest for vscode-languageserver-protocol@3.6.0-next.5 fetched in 26ms
28 silly resolveWithNewModule vscode-languageserver-protocol@3.6.0-next.5 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 41ms (from cache)
30 silly fetchPackageMetaData error for @types/node@^8.0.41 Unexpected end of JSON input while parsing near '...ies":{},"directories"'
31 http fetch GET 304 https://registry.npmjs.org/@types%2fatom 44ms (from cache)
32 silly pacote range manifest for @types/atom@^1.28.0 fetched in 46ms
33 silly resolveWithNewModule @types/atom@1.31.0 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/vscode-jsonrpc 48ms (from cache)
35 http fetch GET 304 https://registry.npmjs.org/vscode-languageserver-types 47ms (from cache)
36 silly pacote version manifest for vscode-jsonrpc@3.6.2 fetched in 50ms
37 silly resolveWithNewModule vscode-jsonrpc@3.6.2 checking installable status
38 silly pacote version manifest for vscode-languageserver-types@3.6.1 fetched in 49ms
39 silly resolveWithNewModule vscode-languageserver-types@3.6.1 checking installable status
40 timing stage:rollbackFailedOptional Completed in 0ms
41 timing stage:runTopLevelLifecycles Completed in 7198ms
42 silly saveTree apm-install-dir-118927-41880-1i5y7bo.qj0a
42 silly saveTree └─┬ ide-typescript@0.7.9
42 silly saveTree   ├─┬ atom-languageclient@0.9.7
42 silly saveTree   │ ├── @types/atom@1.31.0
42 silly saveTree   │ ├── fuzzaldrin-plus@0.6.0
42 silly saveTree   │ ├── vscode-jsonrpc@3.6.2
42 silly saveTree   │ ├─┬ vscode-languageserver-protocol@3.6.0-next.5
42 silly saveTree   │ │ └── vscode-languageserver-types@3.6.1
42 silly saveTree   │ └── vscode-languageserver-types@3.6.1
42 silly saveTree   └── javascript-typescript-langserver@2.11.1
43 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ies":{},"directories"'
43 verbose stack     at JSON.parse (<anonymous>)
43 verbose stack     at parseJson (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
43 verbose stack     at consumeBody.call.then.buffer (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
43 verbose stack     at <anonymous>
43 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
44 verbose cwd /private/var/folders/j2/w28my9055v5672scmxzh8ckm0000gn/T/apm-install-dir-118927-41880-1i5y7bo.qj0a
45 verbose Darwin 18.0.0
46 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/adammenges/.atom/.apm/.apmrc" "--userconfig" "/Users/adammenges/.atom/.apmrc" "install" "https://www.atom.io/api/packages/ide-typescript/versions/0.7.9/tarball" "--runtime=electron" "--target=2.0.7" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
47 verbose node v8.9.3
48 verbose npm  v6.2.0
49 error Unexpected end of JSON input while parsing near '...ies":{},"directories"'
50 verbose exit [ 1, true ]

```

**Comment by damieng** [comment]
Please try uninstalling ide-typescript then installing the new 0.8.0
