### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by kulkarni2u** [atom/ide-typescript#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.1

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/akaranam/.atom/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -2:42.2.0 core:backspace (input.hidden-input)
     -2:31.4.0 core:confirm (input.hidden-input)
     -1:50.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
 65x -0:49.4.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
angular2-snippets 0.4.0 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-ide-ui 0.3.1 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-maven 1.3.0 
atom-spotify2 2.1.2 
atom-typescript 11.0.8 
atom-yeoman 0.3.15 
auto-update-packages 1.0.1 
autocomplete-java 1.2.7 
autocomplete-json 5.5.0 
autocomplete-module-import 0.1.2 
autocomplete-modules 1.7.0 
busy-signal 1.4.3 
docblockr 0.11.0 
editorconfig 2.2.2 
extjs-snippets 0.2.0 
file-icons 2.1.11 
git-projects 1.17.0 
go-plus 5.5.5 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
ide-flowtype 0.17.0 
ide-java 0.6.0 
ide-typescript 0.6.1 
intentions 1.1.5 
language-babel 2.74.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-pgsql 0.2.3 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flow 5.6.1 
linter-golinter 1.2.2 
linter-javac 1.9.4 
linter-jshint 3.1.5 
linter-rubocop 2.1.1 
linter-ruby 1.2.6 
linter-sass-lint 1.7.6 
linter-tslint 1.7.0 
linter-ui-default 1.6.8 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.252.0 
nuclide-format-js 0.0.41 
open-recent 5.0.0 
pigments 0.40.2 
prettier-atom 0.38.0 
react 0.16.2 
react-snippets 0.9.0 
rubocop-auto-correct 1.5.1 
set-syntax 0.3.2 
sort-lines 0.15.0 
synced-sidebar 0.4.3 
term3 0.22.1 
tool-bar 1.1.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, what are the steps to reproduce?

**Comment by damieng** [comment]
No response.
