### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by itome** [atom/ide-typescript#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.1

### Stack Trace

Uncaught SyntaxError: Unexpected token < in JSON at position 1

```
At file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.html:2

SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:210:29)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -7:29.2.0 vim-mode-plus:activate-linewise-visual-mode (input.hidden-input)
  4x -7:29 vim-mode-plus:move-up (input.hidden-input)
     -7:28.2.0 vim-mode-plus:delete-right (input.hidden-input)
 44x -7:27.3.0 vim-mode-plus:move-up (input.hidden-input)
  8x -7:24 platformio-ide-terminal:toggle (input.hidden-input)
 19x -7:14.1.0 vim-mode-plus:move-down (input.hidden-input)
 35x -7:13.2.0 vim-mode-plus:move-up (input.hidden-input)
  2x -7:11.2.0 platformio-ide-terminal:toggle (input.hidden-input)
  5x -6:42.9.0 vim-mode-plus:move-up (input.hidden-input)
 22x -6:42.5.0 vim-mode-plus:move-down (input.hidden-input)
  6x -6:41.2.0 vim-mode-plus:move-up (input.hidden-input)
 30x -6:40.6.0 vim-mode-plus:move-down (input.hidden-input)
 65x -6:19.7.0 vim-mode-plus:move-up (input.hidden-input)
     -6:16.2.0 pane:show-item-1 (input.hidden-input)
     -6:15.7.0 pane:show-item-2 (input.hidden-input)
     -6:13.4.0 core:cancel (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.3.1 
atomatigit 1.5.5 
autocomplete-modules 1.7.0 
autocomplete-paths 2.11.0 
blame 0.12.0 
busy-signal 1.4.3 
disable-keybindings 0.6.0 
file-icons 2.1.11 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
ide-typescript 0.6.1 
intentions 1.1.5 
language-diff 0.7.0 
linter 2.2.0 
linter-ui-default 1.6.8 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
project-manager 3.3.5 
show-ideographic-space 1.0.2 
sync-settings 0.8.3 
vim-mode-plus 1.4.0 
```

**Comment by damieng** [comment]
Can you provide some repro steps?

**Comment by SMLMRKHLMS** [comment]
@damieng This occurred for me when I highlighted a variable name and tried to run "Find References."

**Comment by markovicdenis** [comment]
@damieng same thing happened to me when using "find references".  It seems to work on smaller projects. Maybe there should be an option to exclude some folders like 'bower_componentes', 'node_modules'...

**Comment by damieng** [comment]
No activity or reports of this for some time. If you see this with the most recent version of ide-typescript please comment here so we can re-open this issue.

**Comment by HenrYxZ** [comment]
It also happens to me when using find references (which worked). I'm using macOS 10.13.4 and Atom 1.24.1 with atom-ide-ui. Atom started to process a lot turning on the fan of the computer. And stopped when I closed the find references tabs.
