### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by Hokid** [atom/ide-typescript#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.1

### Stack Trace

Uncaught RangeError: Array buffer allocation failed

```
At buffer.js:43

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:43:12)
    at createUnsafeBuffer (buffer.js:37:25)
    at allocate (buffer.js:189:12)
    at Function.Buffer.allocUnsafe (buffer.js:152:10)
    at Function.Buffer.concat (buffer.js:321:23)
    at MessageBuffer.append (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:48:38)
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:182:21)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -0:09.9.0 intentions:highlight (input.hidden-input)
     -0:09.7.0 window:toggle-dev-tools (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.4.0 
atom-beautify 0.30.5 
atom-file-icons 0.6.0 
atom-ide-ui 0.3.1 
atom-live-server 2.1.2 
atom-ternjs 0.18.3 
atom-wrap-in-tag 0.6.0 
autocomplete-flow 1.6.0 
busy-signal 1.4.3 
change-case 0.6.5 
click-link 1.0.11 
clipboard-history 0.6.6 
color-picker 2.2.5 
double-tag 0.9.0 
editorconfig 2.2.2 
emmet 2.4.3 
expand-selection-to-quotes 0.11.0 
gruvbox-plus-syntax 1.3.1 
html-to-css 0.2.2 
hyperclick 0.0.0 
ide-flowtype 0.17.4 
ide-typescript 0.6.1 
imdone-atom 2.2.6 
intentions 1.1.5 
js-hyperclick 1.11.0 
language-babel 2.74.2 
language-docker 1.1.8 
language-log 1.8.0 
language-nginx 0.8.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.8 
minimap 4.29.6 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
project-plus 1.0.0 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.3 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
vue-hyperclick 0.2.0 
zentabs 0.8.8 
```

**Comment by damieng** [comment]
What were you doing at the time?  Is this reproduce-able?

**Comment by Hokid** [comment]
I don`t know, just open atom and this error show to me. Additionaly, this package produce memory leak after the error show. I did try debug, but atom freezing when the package enabled. I have temporarily disable the package.

**Comment by damieng** [comment]
Unable to repro, no steps. Unactionable.

**Comment by balajiHms** [comment]
I have been facing same issue.
I have created desktop application using electron.In that i have used pptxgen.js which is for making PPT generation using JavaScript.
I got mentioned error and application has been crashed.
"ERROR Error: Uncaught (in promise): RangeError: Array buffer allocation failed"

If anyone knows the solution kindly help me.

**Comment by huanghaiyang** [comment]
> 

+1
