### ISSUE TITLE
Uncaught Error: Message header must separate key and value using :

### ISSUE THREAD

**Issue by lugaramirez** [atom/ide-typescript#38]
[Enter steps to reproduce:]

1. try to open a java project that has submodules on a fresh install of the 1.21.0-beta0 x64 version of atom

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.1

### Stack Trace

Uncaught Error: Message header must separate key and value using :

```
At C:\Users\Gabriel\.atom\packages\ide-typescript\node_modules\vscode-jsonrpc\lib\messageReader.js:68

Error: Message header must separate key and value using :
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (native)
    at MessageBuffer.tryReadHeaders (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:185:43)
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -5:47.7.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:42.1.0 core:confirm (input.hidden-input)
     -5:38.6.0 core:close (input.hidden-input)
     -5:35.7.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:25.5.0 core:confirm (input.hidden-input)
     -4:37.2.0 tree-view:toggle (input.hidden-input)
  2x -4:16.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -4:14.4.0 editor:toggle-line-comments (input.hidden-input)
  2x -4:13.6.0 core:undo (input.hidden-input)
 10x -3:58 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:43.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:40.4.0 editor:consolidate-selections (input.hidden-input)
     -3:40.4.0 core:cancel (input.hidden-input)
  4x -3:26.9.0 tree-view:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
ide-csharp 0.6.0 
ide-flowtype 0.17.4 
ide-java 0.6.0 
ide-typescript 0.6.1 
```

**Comment by damieng** [comment]
No further reports, assuming fixed in newer versions. Please comment here if you get this issue so we can re-open.
