### ISSUE TITLE
Failed to activate the ide-typescript package

### ISSUE THREAD

**Issue by sammihansen** [atom/ide-typescript#45]
[Enter steps to reproduce:]

1. Reloaded atom with new ide package installed

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.1

### Stack Trace

Failed to activate the ide-typescript package

```
At Cannot find module 'atom-languageclient'

Error: Cannot find module 'atom-languageclient'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.20.1/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/ide-typescript/lib/main.js:2:30)
    at /packages/ide-typescript/lib/main.js:112:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.20.1/resources/app/src/config.js:367:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.20.1/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.20.1/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:48.4.0 platformio-ide-terminal:toggle (atom-pane.pane)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-ide-ui 0.4.0 
atom-neon-ui 0.37.1 
atomic-monokai-syntax 1.2.1 
base16-syntax 1.8.1 
color-picker 2.2.5 
dash-syntax 0.4.0 
dash-ui 0.4.3 
emmet 2.4.3 
file-icons 2.1.12 
git-plus 7.9.3 
git-plus-toolbar 1.0.1 
git-status 0.3.4 
gzl-ui 1.0.0 
hacker-dream-syntax 1.4.8 
hacker-dream-ui 1.1.0 
ide-typescript 0.6.1 
ir-black-k-syntax 0.2.3 
keyboard-scroll 0.7.0 
markdown-writer 2.7.2 
minimap 4.29.7 
minimap-pigments 0.2.2 
nucleus-dark-ui 0.12.3 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
pristine-ui 1.1.10 
proton-light 0.2.0 
pure-syntax 0.3.0 
seti-icons 1.5.4 
seti-syntax 1.1.3 
seti-ui 1.9.0 
sync-settings 0.8.3 
tool-bar 1.1.0 
tool-bar-markdown-writer 0.3.0 
```

**Comment by rsese** [comment]
Thanks for the report!  /cc https://github.com/atom/ide-php/issues/13, seems like the same error but different language package?

> Reloaded atom with new ide package installed

How did you install package?

**Comment by sammihansen** [comment]
I did it from the install tab on the settings area of atom.  It looks like you recommend doing it on the command line instead, is that correct?

**Comment by damieng** [comment]
You can install it either way but you should never get the error message you got.  It basically means that Atom did not install the dependencies.  Very strange.

**Comment by damieng** [comment]
I'd try removing and reinstalling and see if that works. If it doesn't you could also try with the `apm` command line too. Let me know if any of these work/fail on your system.

**Comment by damieng** [comment]
No response.

**Comment by Adybo123** [comment]
I was able to replicate this issue by using an old version of Atom, 1.19.0 I believe. updating to 1.21.1 fixes the issue.

**Comment by sammihansen** [comment]
I apologize for the lack of response.  I ended up re-setting up my whole computer. (not because of this issue, just felt like it needed some updating) Once I got set back up and re-installed Atom currently now on 1.21.1 everything is working perfectly.  Thanks!
