### ISSUE TITLE
Uncaught Error: Connection is disposed.

### ISSUE THREAD

**Issue by SShehriyar** [atom/ide-typescript#84]
If i toggle the PyDocStyle option in ide-python package this error comes up.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Pop!_OS 17.10
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.2

### Stack Trace

Uncaught Error: Connection is disposed.

```
At /home/sshehriyar/.atom/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:616

Error: Connection is disposed.
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:616:19)
    at Object.sendNotification (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:386:15)
    at LanguageClientConnection.didChangeConfiguration (/packages/ide-python/node_modules/atom-languageclient/build/lib/languageclient.js:136:10)
    at _disposable.add.atom.config.observe.params (/packages/ide-python/lib/main.js:24:20)
    at /usr/share/atom/resources/app/src/config.js:676:22
    at /usr/share/atom/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:248:20)
    at SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at HTMLInputElement.changeHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:174:25)
```

### Commands

```
  3x -2:32 core:move-down (input.hidden-input)
  2x -2:31.1.0 editor:move-line-up (input.hidden-input)
     -2:30.1.0 core:move-down (input.hidden-input)
     -2:29.2.0 editor:move-line-down (input.hidden-input)
  2x -2:28.4.0 core:move-up (input.hidden-input)
     -2:27.9.0 editor:move-line-down (input.hidden-input)
  2x -2:27.6.0 core:move-up (input.hidden-input)
  3x -2:27.2.0 editor:move-line-down (input.hidden-input)
     -2:23.6.0 core:move-up (input.hidden-input)
     -2:23.3.0 editor:move-line-up (input.hidden-input)
     -2:22.9.0 editor:move-line-down (input.hidden-input)
 47x -2:05.5.0 core:undo (input.hidden-input)
  3x -1:56.3.0 core:backspace (input.hidden-input)
  2x -1:52.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -1:42 core:close (input.hidden-input)
     -1:34.1.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui.teletype-Authenticated)
```

### Non-Core Packages

```
atom-ide-ui 0.7.2 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.1 
file-icons 2.1.16 
highlight-selected 0.13.1 
ide-csharp 0.6.1 
ide-flowtype 0.17.6 
ide-go 0.5.0 
ide-java 0.7.0 
ide-php 0.7.4 
ide-python 0.5.0 
ide-typescript 0.7.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
teletype 0.6.0 
```

**Comment by rsese** [comment]
Thanks for the report - just to confirm, you can reproduce this error by toggling the PyDocStyle option in ide-python package while also using the ide-typescript package or this just happened once?

I was unable to reproduce on Ubuntu 16.04 by toggling the PyDocStyle setting in ide-python while also having ide-typescript installed and a JavaScript file open.

**Comment by SShehriyar** [comment]
@rsese It's gone now 😄. The ide-python package seems to have new options so I'm guessing it got updated and fixed whatever was causing this issue.
